import type * as C from "@hanzo/ui/blocks"

import type PartnersBlock from "@/blocks/def/partners-block"
import type PartnerCardBlock from "@/blocks/def/partner-card-block"

export default {
  blockType: "partners",
  title: {
    blockType: "heading",
    heading: "Leadership",
    level: 3,
    byline: "We are finance and technology pioneers dedicated to building sound financial products that serve the enviroment, society and people.",
    bylineLevel: 0
  } as C.HeadingBlock,
  partners: [
    {
      blockType: "partner-card",
      name: "Zach Kelling",
      title: "CEO",
      description: "A visionary leader in adtech and fintech, Zach leverages quantum encryption for positive environmental and social outcomes. He is prolific as both an engineer and entrepreneur, with over 15 years in high growth startups. He founded Hanzo, a Techstars funded AI marketing platform that launched some of the most successful crowdsales in history, and co-Founded the first SEC approved digital securities platform with Arca, as well as DAOs BrightMoments and DEVxDAO. As CEO of LUX, Zach has pioneered one of the first quantum financial systems. He also actively contributes to influential DAOs and drives societal change, serving on the executive board of the CROP Organization.",
      url: "https://linkedin.com/in/zeekay",
      image: {
        blockType: 'image',
        src: '/assets/images/zach-kelling.png',
        alt: 'Zach Kelling',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Ryan Stobie",
      title: "Chief Business Officer",
      description: "An entrepreneur, investor, and avid adventure seeker, Ryan is a high energy, growth focused, business development manager in the tech sector. With a well-established global network spanning Silicon Valley, Canada, Latin America, and Asia, Ryan has launched and scaled sales teams in multiple sectors upwards of $40 million in revenue. He possesses strong capabilities in early-stage product adoption and go-to-market strategy and values focusing on environmental stewardship.",
      url: "https://www.linkedin.com/in/ryan-stobie",
      image: {
        blockType: 'image',
        src: '/assets/images/ryan-stobie.png',
        alt: 'Ryan Stobie',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Blake Johnson",
      title: "Chief Financial Officer",
      description: "A proven finance professional with an MBA from UC Berkeley's Haas School of Business, Blake has ten years of experience in financial analysis, equity research, and advisory operations roles spanning many industries. His core competencies are in financial modeling and forecasting, investment management, strategic finance, fundraising and investor relations, and industry experience spans technology, media, telecommunications, industrials, and banking.",
      url: "https://www.linkedin.com/in/blake415",
      image: {
        blockType: 'image',
        src: '/assets/images/blake-johnson.png',
        alt: 'Blake Johnson',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Antje Worring",
      title: "Chief Operating Officer",
      description: "Metaverse architect and multidisciplinary designer with over 10 years of experience in art, branding, design, engineering, fashion and marketing as well UI/UX, video production and 3D modeling. She is also an advocate for animal and ocean conservation and has worked in the sustainability sector for over a decade. Antje's career began at award-winning Karma Bikinis, where she has served as CEO & lead designer since 2014, producing over 300 products and hundreds of photo shoots. Since March 2020, she has also worked as designer, software engineer and delivers multidisciplinary activations, engagements and partnerships, while never losing focus on growth.",
      url: "https://www.linkedin.com/in/antje-worring",
      image: {
        blockType: 'image',
        src: '/assets/images/antje-worring.jpg',
        alt: 'Antje Worring',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Ashley Christie",
      title: "Chief of Staff",
      description: "Ashley Kathleen Christie is the Chief of Staff at Lux Partners Limited, where she leverages her diverse experience in military operations and private wealth management to drive digital finance and lifestyle ventures. At Lux, she has been pivotal in integrating advanced technologies like renewable Bitcoin mining and quantum-secure systems into global strategies. Notably, Ashley led the launch of the Lux Credit Card, enhancing financial utility with wealth-building features. Her previous role at Carbon Nation saw her pioneering the Carbon-Based Agro Metaverse Game, merging gaming with environmental sustainability. Ashley's expertise in operations and her strategic vision continue to shape Lux’s trajectory in the blockchain space.",
      url: "https://www.linkedin.com/in/ashley-kathleen-christie",
      image: {
        blockType: 'image',
        src: '/assets/images/ashley-christie.png',
        alt: 'Ashley Christie',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Christopher Dinelli",
      title: "Chief Information Officer",
      description: "Former US Navy Lieutenant and United States Naval Academy alumnus with an Aerospace Engineering background, expansion into blockchain mining and AI cloud services and infrastructure, forging pivotal partnerships within the generative AI and cloud domains. As the founder of All Mine Lah, Inc., Chris innovatively melded green energy with digital currency mining, advancing sustainable supercomputing solutions. Renowned for his data analysis acumen and Matlab expertise, Chris's leadership style, rooted in military principles, champions innovation, ethical practices, and security, solidifying Lux's stature in blockchain and finance, reflecting his overarching commitment to responsible technological growth.",
      url: "https://www.linkedin.com/in/christopher-dinelli-0152578b",
      image: {
        blockType: 'image',
        src: '/assets/images/christopher-dinelli.png',
        alt: 'Christopher Dinelli',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Ling Qing Meng",
      title: "Chief Technology Officer",
      description: "Ling Qing worked at Edenledger as a CTO, cybersecurity advisor to Beamswap and software engineer at Branch.io. His role was focused on go to market launch for shipping mission critical features for the marketing products at these firms. He has experience working at Decentral which has built MEV bots for funds such as Whalepod. In settings where he was competing with the best of the best in the world, Ling has the know-how and track record of consistently coming out on top.",
      url: "https://www.linkedin.com/in/lingqingmeng",
      image: {
        blockType: 'image',
        src: '/assets/images/ling-qing-meng.png',
        alt: 'Ling Qing Meng',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Lori Luttrell",
      title: "Chief Data Scientist",
      description: "As a data scientist, Lori’s expertise in research is matched by her strategic business intellect. With an academic background in the biological sciences, she brings a unique perspective that bridges the gap between tech and real world applications. She navigates complex systems and identifies opportunities for collaboration that drive innovation forward. Her experience in a diversity of industries includes scientific research and advisory roles in emerging biotechnologies, Big Data, AI, and the health and wellness sector. As a numismatist, her interests cross into fintech and currency trends. A systems thinker with a strong work ethic, she is dedicated to leveraging data driven strategies towards the responsible growth of beneficial technologies.",
      url: "https://www.linkedin.com/in/lorijluttrell/",
      image: {
        blockType: 'image',
        src: '/assets/images/lori-luttrell.png',
        alt: 'Lori Luttrell',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Justin Gawn",
      title: "Chief Strategy Officer",
      description: "With 24 years of industry experience, he has proven his adeptness at identifying capital market trends, and delivering profitable trading and growth strategies for midcap and large junior mining companies. His diverse roles in institutional sales, investment advising, and trading allowed him to gain deep insights and experience in crafting risk-adjusted portfolios and his efficient execution of trading strategies have solidified his reputation in the sector.",
      url: "https://www.linkedin.com/in/justin-gawn-43687b1b/?originalSubdomain=ca",
      image: {
        blockType: 'image',
        src: '/assets/images/justin-gawn.png',
        alt: 'Justin Gawn',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Skyler Trotter",
      title: "Chief Innovation Officer",
      description: "Sky is a renowned blockchain innovator and the co-founder of EOS Bake, where he has made significant strides in decentralized sovereignty and blockchain infrastructure. His career spans critical roles at the EOS Incubator, Polyient Labs, W1SE Logistics, EX3.io, Coin Dealer, and Strawberry DAC, contributing immensely to the blockchain sector. At the EOS Incubator, Sky's mentorship of emerging blockchain projects showcased his deep technical knowledge, crucial in fostering startup growth within the complex blockchain ecosystem. His role at Polyient Labs was instrumental in developing pioneering decentralized finance (DeFi) solutions, merging financial expertise with blockchain innovation.",
      url: "https://www.linkedin.com/in/sky-trotter-b86a74244",
      image: {
        blockType: 'image',
        src: '/assets/images/skyler_trotter.png',
        alt: 'Skyler Trotter',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Jack Kochen",
      title: "Chief Marketing Officer",
      description: "Jack has been running communities since he was young, and has been a blockchain hobbyist since 2012! Jack's last project was the first DeFi application on Cardano, VyFinance. He has also worked alongside Moonpay, Vechain, and a swath of smaller projects. Jack's expertise ranges far and wide, from programming in Golang, to running a community, to operational logistics; and all the marketing required between. Focusing on efficiency, trust, transparency, and 'cult following' styles, Jack hopes to make Lux a household-name.",
      url: "https://www.linkedin.com/in/jack-kochen/",
      image: {
        blockType: 'image',
        src: '/assets/images/jack-kochen.png',
        alt: 'Jack Kochen',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Dara Gallopin",
      title: "Chief Creative Officer",
      description: "Dara Gallopin is a Swiss-Iranian interdisciplinary artist with a unique vision shaped by his nomadic lifestyle across the globe. Formally trained at the École Cantonale d'Art de Lausanne (ECAL), Dara's expertise spans multiple disciplines, from abstract geometric drawings to intricate sculptures and digital artworks. His artistic approach, deeply influenced by his diverse cultural experiences, integrates innovative technologies like 3D scanning and digital manipulation, seamlessly blending traditional art forms with cutting-edge methods. This adaptive and inclusive style embodies the values of Lux, pushing boundaries in creativity and technological integration, aiming to foster a universal and dynamic engagement with art.",
      url: "https://www.daragallopin.com/",
      image: {
        blockType: 'image',
        src: '/assets/images/dara-gallopin.png',
        alt: 'Dara Gallopin',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Artem Ash",
      title: "Lead Architect",
      description: "From helping build the first browser plugin for VR in the 90s, to innovating advanced UI generation for FinTech in the 2000's, Artem Ash has a decades-long track record of delivering powerful and elegant solutions. He’s thus insistent on developing an app's core in isolation from the idiosyncracies of many technologies, API models, or data solutions. With a long-standing appreciation of Product Design, he’s able to bridge the gaps between various stake-holders and get things moving forward. A proven technical leader, Artem successfully runs and manages teams via a strong belief in sharing expertise and imparting positive core habits to other developers.",
      url: "https://www.linkedin.com/in/artem-ash-1008/",
      image: {
        blockType: 'image',
        src: '/assets/images/artem-ash.png',
        alt: 'Artem Ash',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Ari Lerner",
      title: "VP Engineering",
      description: "Ari is a passionate software engineer, entrepreneur, and educator. With over 20 years of experience, he has co-founded successful companies like Fullstack.io and Fieldday. As a senior consultant at Amazon Web Services, Ari guides clients in application development and has extensive experience in technology. He is a respected author, having written over ten books on programming, and shares his insights at global tech conferences. His notable works include co-authoring D3 on AngularJS, Zero to Deep Learning, and Fullstack React, Native, & Vue.",
      url: "https://www.linkedin.com/in/arilerner",
      image: {
        blockType: 'image',
        src: '/assets/images/ari-lerner.png',
        alt: 'Ari Lerner',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Woo Bin",
      title: "VP Engineering",
      description: "Woo Bin is a seasoned software developer with seven years of experience specializing in full-stack web app, dApp development, and AI chat app. He currently holds the position of Lead Engineer at Lux Network, where he brings a distinguished understanding of various programming languages and infrastructures. His extensive experience lies in creating high-performing, scalable software products, and applications tailored for unique business needs. Undeniably, Woo Bin is a savvy problem solver and tech enthusiast always at the forefront of technological innovations. His work influencers efficient workflow and fosters cutting-edge technological advancements in the software industry.",
      url: "https://lux.partners",
      image: {
        blockType: 'image',
        src: '/assets/images/woo-bin.png',
        alt: 'Woo Bin',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Jason Xu",
      title: "VP Engineering",
      description: "Jason is a seasoned full-stack developer with nine years of experience, specializing in frontend and iOS development. Skilled in React, Vue, JavaScript, and TypeScript, he has a proven track record of leading dynamic teams and delivering pivotal projects across various platforms, including web and mobile applications. Jason's deep technical expertise extends to the ReactNative framework, where he excels in package separation, componentization, and native module encapsulation, allowing him to adeptly navigate and efficiently solve complex development challenges. His innovative approach and commitment to excellence have made him a valuable asset in driving technological advancements and enhancing user experiences.",
      url: "https://lux.partners",
      image: {
        blockType: 'image',
        src: '/assets/images/jason-xu.png',
        alt: 'Jason Xu',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Jackson Mori",
      title: "VP Engineering",
      description: "Experienced full-stack and blockchain developer with a proven track record of designing, developing, and deploying robust, scalable, and secure web and blockchain-based applications. Proficient in a wide range of programming languages, frameworks, and technologies, including JavaScript, React, Node.js, Solidity, Ethereum, and various databases. Skilled in agile software development methodologies, DevOps practices, and cloud computing. Passionate about staying up-to-date with the latest industry trends and technologies to deliver innovative solutions that meet or exceed client requirements",
      url: "https://lux.partners",
      image: {
        blockType: 'image',
        src: '/assets/images/jackson-mori.png',
        alt: 'Jackson Mori',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Michael Filteau",
      title: "Operations Lead",
      description: "Michael comes from a background as an IT Technician and Crypto Miner. He brings a wealth of experience across various industries, marked by his adaptive approach and innovative solutions. With a foundational interest sparked by his first Mac, Michael’s journey into technology has been largely autodidactic, allowing him to think outside the box and deliver unique solutions. His early forays into cryptocurrency mining during the initial release of Ethereum highlight his forward-thinking and pioneering spirit in adopting new technologies. Michael’s diverse industry experience has honed his ability to adapt and excel in different technological environments, making him a versatile and valuable asset.",
      url: "https://lux.partners",
      image: {
        blockType: 'image',
        src: '/assets/images/michael-filteau.png',
        alt: 'Michael Filteau',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Fernando Barrajon",
      title: "Designer",
      description: "Fernando Barrajón is a UX Lead with 8 years of experience in Banking and Fintech and a degree in Interaction Design. He excels in visual and verbal storytelling, UX design, product management, and agile methodologies. He has a strong background in creating prototypes to align stakeholders and drive decision-making, facilitating workshops, and training cross-functional teams. He has also contributed to the design of various innovative digital products and platforms. He is skilled in Figma, Product Development, User Research, and more.",
      url: "https://www.linkedin.com/in/fbarrajon/",
      image: {
        blockType: 'image',
        src: '/assets/images/fernando-barrajon.png',
        alt: 'Fernando Barrajon',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Cyrus Pahlavi",
      title: "Executive President",
      description: `An accomplished artist, inventor, human rights advocate, and expert in global finance and commodities, Cyrus brings a wealth of experience and a unique perspective to his role as Executive President of LUX. His diverse career, highlighted by significant achievements in art, activism, philanthropy, film production, and diplomacy, is underpinned by a robust global network cultivated through prestigious education at Le Rosey in Switzerland and Parsons College. This network, enriched by his lineage as a descendant of the "Peacock Dynasty" and his advocacy for women's rights, aligns with the legacy of Cyrus the Great and his pioneering human rights efforts.`,
      url: "https://www.cyruspahlavi.com/about",
      image: {
        blockType: 'image',
        src: '/assets/images/cyrus-pahlavi.png',
        alt: 'Cyrus Pahlavi',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
    {
      blockType: "partner-card",
      name: "Ole Brereton",
      title: "Executive VP",
      description: "Lord Ole Loftus Brereton is an accomplished Executive with a strong background in Finance, International Trade, Production, Music Videos, Advertising, and Design. As Executive Vice President at LUX since May 2021, he spearheads private asset management and wealth solutions, fostering success in an ever-evolving world. Based in the Isle of Man and London, Ole's visionary leadership has been instrumental in shaping Lux's growth, driving innovation in asset management and regulated technology over two fruitful years.",
      url: "https://www.linkedin.com/in/lord-ole-loftus-l-brereton-911a1a11",
      image: {
        blockType: 'image',
        src: '/assets/images/ole-brereton.png',
        alt: 'Ole Brereton',
        dim: { w: 100, h: 100 },
      } as C.ImageBlock,
    } as PartnerCardBlock,
  ]
} as PartnersBlock
